"""Add DoctorAvailability model with correct fields

Revision ID: ff2028f82ac0
Revises: 9b6fc2fe657c
Create Date: 2025-04-16 20:27:31.467500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2028f82ac0'
down_revision = '9b6fc2fe657c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('availability_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_from', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('available_to', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('is_booked')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('availability_id',existing_type=sa.INTEGER(),nullable=False)

    # ### end Alembic commands ###
